/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sesante
 */
public class landingOptions extends javax.swing.JFrame {

    /**
     * Creates new form landingOptions
     */
    public landingOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewProduct = new javax.swing.JLabel();
        addProduct = new javax.swing.JLabel();
        addToCart = new javax.swing.JLabel();
        viewShoppingCart = new javax.swing.JLabel();
        checkOut = new javax.swing.JLabel();
        viewOrders = new javax.swing.JLabel();
        viewPoduct = new javax.swing.JButton();
        addProducButton = new javax.swing.JButton();
        addToCartButton = new javax.swing.JButton();
        viewCartButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();
        viewOrdersButton = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();
        LogOut = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backGroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-view-80.png"))); // NOI18N
        jPanel1.add(viewProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        addProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-food-receiver-80.png"))); // NOI18N
        jPanel1.add(addProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        addToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-shopping-cart-80.png"))); // NOI18N
        jPanel1.add(addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        viewShoppingCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-view-80 (1).png"))); // NOI18N
        jPanel1.add(viewShoppingCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 80, 80));

        checkOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-check-out-80.png"))); // NOI18N
        jPanel1.add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, 90));

        viewOrders.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logistics-80.png"))); // NOI18N
        jPanel1.add(viewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, -1));

        viewPoduct.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewPoduct.setText("View product");
        viewPoduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPoduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPoductActionPerformed(evt);
            }
        });
        jPanel1.add(viewPoduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, 30));

        addProducButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addProducButton.setText("Add Product");
        addProducButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProducButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProducButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addProducButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, 30));

        addToCartButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addToCartButton.setText("Add to cart");
        addToCartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addToCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addToCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, 30));

        viewCartButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewCartButton.setText("View shopping cart");
        viewCartButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewCartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCartButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewCartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, 30));

        checkOutButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        checkOutButton.setText("Check Out");
        checkOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(checkOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, 30));

        viewOrdersButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewOrdersButton.setText("View all Orders");
        viewOrdersButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewOrdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersButtonActionPerformed(evt);
            }
        });
        jPanel1.add(viewOrdersButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, -1, 30));

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-100.png"))); // NOI18N
        jPanel1.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        LogOut.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        LogOut.setForeground(new java.awt.Color(255, 0, 0));
        LogOut.setText("LOG OUT");
        LogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });
        jPanel1.add(LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        home.setForeground(new java.awt.Color(9, 148, 65));
        home.setText("HOME");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 80, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to the E-commerce Platform!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel2.setText("Click your way to Happines, changing the way you shop!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Exit");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 30, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153, 80));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 530, 280));

        backGroundImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backGroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/photo-1495085461086-ae0ad0a8fd74-1344x734.jpg"))); // NOI18N
        jPanel1.add(backGroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addProducButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProducButtonActionPerformed
        // TODO add your handling code here:
        addProduct add = new addProduct();
        add.show();
        
        dispose();
    }//GEN-LAST:event_addProducButtonActionPerformed

    private void viewPoductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPoductActionPerformed
        // TODO add your handling code here:
        viewProductListing view = new viewProductListing();
        view.show();
        
        dispose();
    }//GEN-LAST:event_viewPoductActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        // TODO add your handling code here:
        checkOut checkOutOrders = new checkOut();
        checkOutOrders.show();
        
        dispose();
    }//GEN-LAST:event_checkOutButtonActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        landingOptions options = new landingOptions();
        options.show();
        
        dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void addToCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartButtonActionPerformed
        // TODO add your handling code here:
        addToCart addCart = new addToCart();
        addCart.show();
        
        dispose();
    }//GEN-LAST:event_addToCartButtonActionPerformed

    private void viewCartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCartButtonActionPerformed
        // TODO add your handling code here:
        viewShoppingCart viewCart = new viewShoppingCart();
        viewCart.show();
        
        dispose();
    }//GEN-LAST:event_viewCartButtonActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        // TODO add your handling code here:
        dashBoard logOut = new dashBoard();
        logOut.show();
        
        dispose();
    }//GEN-LAST:event_LogOutActionPerformed

    private void viewOrdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersButtonActionPerformed
        // TODO add your handling code here:
        viewAllOrders viewOrders = new viewAllOrders();
        viewOrders.show();
        
        dispose();
    }//GEN-LAST:event_viewOrdersButtonActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landingOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landingOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landingOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landingOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landingOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOut;
    private javax.swing.JButton addProducButton;
    private javax.swing.JLabel addProduct;
    private javax.swing.JLabel addToCart;
    private javax.swing.JButton addToCartButton;
    private javax.swing.JLabel backGroundImage;
    private javax.swing.JLabel checkOut;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel userIcon;
    private javax.swing.JButton viewCartButton;
    private javax.swing.JLabel viewOrders;
    private javax.swing.JButton viewOrdersButton;
    private javax.swing.JButton viewPoduct;
    private javax.swing.JLabel viewProduct;
    private javax.swing.JLabel viewShoppingCart;
    // End of variables declaration//GEN-END:variables
}
